---
title: "Analysis1"
output: html_document
date: "2026-01-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(dplyr)
library(bipartite)
library(ggplot2)
library(ggeffects)
library(ggrepel)
library(tidyverse)
library(vegan)
library(reshape2)
library(readxl)
library(cluster)

```

```{r}
# read in cleaned data
pollinators <- read.csv("Pollinator_data_cleaned.csv")
seeds <- read.csv("Cleaned_seeds.csv")

pollinators$BP <- paste0(pollinators$Block, pollinators$Plot)
seeds$BP <- paste0(seeds$Block, seeds$Plot)
  
# get unique treatments from seed data and name empty list
trts <- unique(seeds$genSpec)

clist <- vector(mode='list', length=length(trts)) #list of communities (treatments)
names(clist) <- trts  #naming the parts of the list the name of the treatment group 

plist <- vector(mode='list', length=15)
names(plist) <- unique(paste(trts, seeds$Block, sep = "_"))  #naming the list 

# create for loop to make each item in list contain block and plots from that treatment
for (tt in trts){
  tmp <- seeds[seeds$genSpec==tt,]
  bp <- unique(tmp$BP)

# create adjacency matrix for each item in list (community) 
  polls <- pollinators[pollinators$BP %in% bp,]
  ppmat <- as.matrix(table(polls$sp, polls$Genus))
  clist[[tt]] <- ppmat
  
for (b in bp){
  select <- paste(tt, substr(b,1,1), sep = "_")
  blockpolls <- polls[polls$BP ==b,]
  ppmatB <- as.matrix(table(blockpolls$sp, blockpolls$Genus))
  plist[[select]] <- ppmatB
}}

#whole experiment network:
pp_all <- as.matrix(table(pollinators$sp, pollinators$Genus))

# find average Open - Closed per plant per group 
zeros <- seeds[,c('OsPerb','CsPerb')]==0 
seeds[,c('OsPerb','CsPerb')][zeros] <- NA 

# find means, differences and ratios of pollinator impact 
seedsGrouped <- seeds %>%
  mutate(ratio_poll_impact = OsPerb/CsPerb) %>%
  group_by(sp, BP) %>%
  mutate(ratio_seedsPerPlant = mean(ratio_poll_impact, na.rm = TRUE)) %>%
  distinct(BP, genSpec, sp, ratio_seedsPerPlant) # remove unneccesary collumns

# add treatment column 
seedsGrouped$treatment <- paste(seedsGrouped$genSpec, substr(seedsGrouped$BP,1,1), sep = "_")

pollsSeedsdf <- seedsGrouped %>%
  inner_join(pollinators, by = c("BP", "sp"), relationship = "many-to-many") %>%
  select(-c(Block, Plot, sp.no)) 

```

Network analysis by block -> group level 

```{r}
# find network and group level characteristics (by block/plot)
H_values <- lapply(plist, networklevel, index = "H2")
nestedness <- lapply(plist, networklevel, index = "nestedness")
niche_overlap <- lapply(plist, grouplevel, level ="both", index = "niche overlap")
Total_niche <- networklevel(pp_all, level ="both", index = "niche overlap")

# convert list of metrics to data frame (by by block/plot)
H_values <- as.data.frame(H_values)
nestedness <- as.data.frame(nestedness)
niche_overlap <- as.data.frame(niche_overlap)
Total_niche <- as.data.frame(Total_niche)

# create function to rename and which overlap is which and rearrange df  
rename.levels <- function(df, metric){
  new_df <- df %>% 
  tibble::rownames_to_column("group")
  new_df$group <- ifelse(grepl("HL", new_df$group), "pollinators", "plants")
  new_df <- pivot_longer(new_df, cols = -group, names_to = "treatment", values_to = metric)
  return(new_df) 
}

# make characteristics into dfs 
nichedf <- rename.levels(niche_overlap, "overlap")
Hdf <- rename.levels(H_values, "H2")
nestednessdf <- nestedness %>%
  tibble::rownames_to_column("metric") %>%
  pivot_longer(cols = -metric, names_to = "treatment", values_to = "nestedness") %>%
  select(-metric)
nichedfwide <- nichedf %>%
  pivot_wider(id_cols = "treatment",names_from = "group", values_from = "overlap") %>%
  rename("pollOverlap" = pollinators,
         "plantOverlap" = plants)

colnames(Total_niche)[1] <- "overlapNet"
rownames(Total_niche) <- c("pollinators", "plants")
Total_niche <- Total_niche %>%
  tibble::rownames_to_column("group")

# calculate total pollinator visitation per block  
visitation <- vector(mode ="logical", length = length(plist)) 
for(i in seq_along(plist)){
   this.mat <- as.matrix(plist[[i]])
   visitation[i] <- sum(this.mat)
 }
visitation <- data.frame( 
  treatment = names(plist), 
  total_visits = visitation )

# calculate species richness
richness <- vector(mode ="numeric", length =length(plist)) 
for (i in seq_along(plist)){
  this.logMat <- as.logical(plist[[i]])
  richness[i] <- sum(this.logMat)
}
richness <- data.frame( 
  treatment = names(plist), 
  richness = richness )

# Join all characteristics toegther into df
Whole_df <- nichedfwide %>%
  inner_join(richness, by = "treatment" ) %>%
  inner_join(visitation, by = "treatment" ) %>%
  inner_join(nestednessdf, by = "treatment") %>%
  inner_join(Hdf, by = "treatment", relationship = "many-to-many") %>%
  inner_join(Total_niche, by = "group", relationship = "many-to-one")

  
# combine all data 
focalSeeds <- seedsGrouped %>% 
  pivot_wider(names_from = sp, values_from = ratio_seedsPerPlant) %>%
  inner_join(Whole_df, by = "treatment")

# pivot df wider for tidyness 
spNames <- unique(seeds$sp)
WIDEfocalSeeds <- focalSeeds %>%
   pivot_longer(cols = all_of(spNames), names_to = "sp", values_to = "seedOutput") %>%
   rowwise() %>%
   mutate(AVoverlap = mean(c(pollOverlap,plantOverlap))) %>%
  select(-group)

```

Visualise Whole Networks 

```{r}
# visualise network as heatmap
library(RColorBrewer)
cols <- hcl.colors(15, "Hawaii")
cols2 <- hcl.colors(15, "Red-Yellow", rev = TRUE)

# heat map per treatment 
lapply(clist, visweb, square = "defined", box.col = "black", def.col = cols2, labsize = 0.8, text = "interaction", textcol = "black", NA.col = "white")

# make overlap models
lapply(clist, plotweb, empty = TRUE, higher_color = cols, lower_color = cols, text_size = 0.8, srt = 90)


```


seed plotting - make sure to change lm1 depending on relationship being plotted

```{r}
# plot overlap against seed ratios, sep = species 
ggplot(WIDEfocalSeeds, aes(x = AVoverlap, y = seedOutput, color = genSpec)) +
  geom_point() +
  facet_wrap(~sp) +
  labs(x="Overlap") 

# Overlap against seed ratios for all treatments and species 
lm1 = lm(WIDEfocalSeeds$seedOutput~WIDEfocalSeeds$AVoverlap)
ggplot(WIDEfocalSeeds, aes(x = AVoverlap, y = seedOutput, color = genSpec, shape = sp)) +
  geom_point() +
  geom_abline(intercept = coef(lm1)[1], slope = coef(lm1)[2], color = "red") +
    geom_text(aes(x = 0.75, y = 1.5, label = "p = 0.568"), 
            color = "red", vjust = -1) +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  labs(x="Overlap", y = "Seed Output", color = "Treatment", shape = "Flower Species") 

# plot overlap for treatments
ggplot(WIDEfocalSeeds, aes(x = genSpec, y = AVoverlap, fill = genSpec)) +
  geom_boxplot() +
  stat_summary(fun = median, geom = "text", aes(label = round(..y.., 2)), vjust = -0.5) +
  labs(x="Treatment", y = "Overlap") 

ggplot(WIDEfocalSeeds, aes(x = genSpec, y = AVoverlap, fill = genSpec)) +
  geom_boxplot()+ 
  stat_summary(fun = median, geom = "text", aes(label = round(..y.., 2)), vjust = -0.5) +
  labs(x="Treatment", y = "Overlap") 

#plot seed ratios for treatments
ggplot(WIDEfocalSeeds, aes(x = genSpec, y = seedOutput, fill = genSpec)) +
  geom_boxplot() +
  stat_summary(fun = median, geom = "text", aes(label = round(..y.., 2)), vjust = -0.5) +
  labs(x="Treatment", y = "Seeds")

# plot visits against overlap 
lm2 <- lm(WIDEfocalSeeds$richness~WIDEfocalSeeds$total_visits)
ggplot(WIDEfocalSeeds, aes(x = total_visits, y = richness, color = genSpec)) +
  geom_point() +
  geom_abline(intercept = coef(lm2)[1], slope = coef(lm2)[2], color = "red") +
  labs(x="visits", y = "richness")

# plot overlap and H2
lm4 <- lm(WIDEfocalSeeds$H2~WIDEfocalSeeds$AVoverlap)
  
ggplot(WIDEfocalSeeds, aes(x = AVoverlap, y = H2, color = genSpec)) +
  geom_point() +
  geom_abline(intercept = coef(lm4)[1], slope = coef(lm4)[2], color = "red")

```
Plot seed output per species per treatment 

```{r}
library(ggbiplot)

ggplot(WIDEfocalSeeds) +
   geom_point(aes(x = AVoverlap, y = log(seedOutput), color = sp)) +
  #facet_wrap(~genSpec) +
   labs(y ="Seed output", x = "overlap", title = "Reproductive Output: Treatment")

# PCA for group-level
PCdf <- WIDEfocalSeeds %>%
  ungroup() %>% 
  select(c("richness", "total_visits", "AVoverlap", "nestedness", "H2", "plantOverlap", "pollOverlap")) %>%
  rename(Richness = "richness", Visitation = "total_visits", AverageOverlap = "AVoverlap", PollinatorOverlap = "pollOverlap", PlantOverlap = "plantOverlap", Nestedness = "nestedness")

PCAG <- prcomp(PCdf, scale. = TRUE)
biplot(PCAG, var.axes = TRUE, cex = 1, xlim = c(-0.3,0.3), ylim = c(-0.3,0.3))


WIDEfocalSeedsPCA <- cbind(WIDEfocalSeeds, PCAG$x[,1:2])


# PCA for species level 
PCdfSP <- speciesDF %>%
  ungroup() %>%
  select(c("degree", "PSI", "specialization"))

PCAS <- prcomp(PCdfSP, scale. = TRUE)
biplot(PCAS)

speciesPCA <- cbind(speciesDF, PCAS$x[,1:2])

ggplot(WIDEfocalSeedsPCA) +
  geom_point(aes(x = PC1, y = PC2, color=genSpec))

ggplot(WIDEfocalSeedsPCA) +
  geom_point(aes(x = PC1, y = seedOutput, color = sp))

ggplot(speciesPCA) +
  geom_point(aes(x = PC2, y = PC1, color = genSpec))

```

 Try to make NMDS

```{r}
# nmds_data <- allCHAR %>%
#   select(genSpec,
#          BP,
#          richness,
#          total_visits,
#          nestedness,
#          H2,
#          degree,
#          specialization,
#          AVoverlap,
#          PSI)
# 
# # Convert categorical variables to factors
# nmds_data <- nmds_data %>% 
#   mutate(across(c(richness,
#          total_visits,
#          nestedness,
#          H2,
#          degree,
#          specialization,
#          AVoverlap,
#          PSI), as.factor))
# 
# 
# gower_dist <- nmds_data %>%
#   ungroup() %>% 
#   select(-genSpec, -sp, -BP) %>%
#   daisy(metric = "gower")
#   
# 
# set.seed(123)  # reproducibility
# 
# nmds <- metaMDS(
#   gower_dist,
#   k = 2,
#   trymax = 100,
#   autotransform = FALSE
# )
# 
# # Check stress
# nmds$stress
# 
# scores_df <- as.data.frame(scores(nmds))
# scores_df$BP <- nmds_data$BP
# scores_df$genSpec <- nmds_data$genSpec
# 
# ggplot(scores_df, aes(x = NMDS1, y = NMDS2, color = genSpec)) +
#   geom_point(size = 3, alpha = 0.85) +
#   
#   # ⬇️ ADD THIS LINE
#   stat_ellipse(type = "t", level = 0.95, linewidth = 1) +
#   
#   theme_minimal() +
#   labs(
#     title = "NMDS of community characteristics",
#     subtitle = paste("Stress =", round(nmds$stress, 3)),
#     color = "genSpec"
#   ) +
#   theme(
#     text = element_text(size = 12),
#     legend.position = "right"
#   )

```


dissimilarity?

```{r}
#calculate total interactions for each unique pol-plant pair##
# plant_association <- polls %>%
#   mutate(across(where(is.character), str_trim)) %>%
#   group_by(Genus, sp, BP) %>%
#   summarise(count = n(), .groups = "drop")
# 
# association_dta <- plant_association %>%
#   group_by(Genus, sp) %>%
#   summarize(count = round(mean(count)), .groups = "drop") %>%
#    pivot_wider(
#     names_from = sp,
#     values_from = count,
#     values_fill = 0)
# 
# association_matrix <- association_dta  %>%
#   select(-(Genus))
#            
# bee_names <- association_dta$Genus
# rownames(association_matrix) <- bee_names
# association_matrix[association_matrix > 0] <- 1
# 
# set.seed(1)
# jaccard_diss <- vegdist(t(association_matrix), method = "jaccard")
# jaccard_matrix <- as.matrix(jaccard_diss)
# sort(colSums(jaccard_matrix), decreasing = TRUE)
# jaccard_long <- reshape2::melt(as.matrix(jaccard_matrix))
# 
# jaccard_plot <- jaccard_long %>%
#   as.data.frame() %>%
#   ggplot(aes(x = Var1, y = Var2, fill = value)) +
#   geom_tile() +
#   scale_fill_viridis_c(option = "viridis") +
#   theme_minimal() +
#   theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
#   labs(x = NULL, y = NULL, fill = "Dissimilarity Index")
# 
# jaccard_plot

```

