---
title: "Data_Cleaning"
output: html_document
date: "2026-01-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(dplyr)
```

Cleaning seed data to remove incomplete data points 
```{r}
bigseeds <- read.csv("/Users/sydneyjames/OneDrive_UniversityofOregon/Thesis_Data /pollinator_sharing2026/RFseed_data - Sydney RF seeds.csv")

# convert empty or 0 blooms to NAs
bigseeds$Cblooms <- as.integer(bigseeds$Cblooms)
bigseeds["Oblooms" == ""| "Oblooms" == 0] <- NA
bigseeds["Cblooms" == ""| "Cblooms" == 0] <- NA

# remove NAs  
completeseeds <- bigseeds %>%
  drop_na(Cblooms, Oblooms) %>%
  mutate(OsPerb = total.open/Oblooms, 
         CsPerb = total.closed/Cblooms)

# select only needed columns 
neededData <- subset(completeseeds, 
                     select = c(Block, Plot, genSpec, sp, fc, OsPerb, CsPerb))

# split into each treatment
treatment_df <- split(neededData, neededData$genSpec, drop = FALSE)

# make every treatment into adjaceny matrix list
WHOLE_LIST <- vector("list", length = length(treatment_df))
for(i in seq_along(treatment_df)){
 ThisMix <- treatment_df[[i]] %>%
  ungroup() %>%
 # complete(Plant = all_plants, Pollinator = all_pollinators, fill = list(interactions = 0)) %>%
  group_by(sp) %>%
  summarize(interactions = n(), .groups = "drop") %>%
 # pivot_wider(names_from = Pollinator, values_from = interactions, values_fill = 0) %>%
 # column_to_rownames( var = "Plant")
 # ThisMix[is.na(ThisMix)] <- 0
# ThisMix[ThisMix == 1] <- 0
  WHOLE_LIST[[i]] <- ThisMix
  names(WHOLE_LIST) <- names(Stand_df)
}

```
 
 Read in Bee data and prepare to be joined to seed data 
```{r}
BeeNos <- read.csv("/Users/sydneyjames/OneDrive_UniversityofOregon/Thesis_Data /pollinator_sharing2026/BEE IDs - RF 24 - Sheet1.csv") 

BeePlants <- read.csv("/Users/sydneyjames/OneDrive_UniversityofOregon/Thesis_Data /pollinator_sharing2026/Specimens_Riverfront_JA - Sheet1.csv")

# remove uneeded columns
BeePlantsOnly <- subset(BeePlants, select = -c (FreezerBoxNum, Collector, SampleRound, Date, Year, Notes))

# rename to match ID data 
BeePlantsOnly <- BeePlantsOnly %>%
  rename("sp.no" = Unique.ID, 
          "plant" = FieldPlantID)  

# join Bee plants to genus (Run this to reset all pollinators)
Pollinators <- BeePlantsOnly %>%
  inner_join(BeeNos)

# remove all non-pollinators (keep syrphid genera only) 
EffPollinators <- Pollinators %>%
  filter(!Genus %in% c("unidentifiable ", "beetle larve", "gymnosoma", "rhamphomyia ", "cylindromyia"))
 
```