---
title: "Untitled"
output: html_document
date: "2026-02-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(dplyr)
library(bipartite)
library(ggplot2)
library(ggeffects)
library(ggrepel)
library(ggridges)
```



```{r cars}

# find degree for each plant/poll in each treatment  

allpolls <- unique(pollinators$Genus)
allplants <- unique(pollinators$sp)
allsp <- c(allpolls, allplants)
BP <- unique(pollsSeedsdf$BP)

trtVersions <- data.frame(
  treatment = seedsGrouped$treatment, 
  genSpec = seedsGrouped$genSpec)

bigmat <- matrix(NA, nrow = length(plist), ncol = length(allsp), dimnames = list(names(plist), allsp))
for (i in names(plist)) {
  degree <- specieslevel(plist[[i]], level = "both", index = "degree")
  polls1 <- degree$`higher level`
  plants1 <- degree$`lower level`
  bigmat[i,rownames(polls1)] <- unlist(polls1)
  bigmat[i,rownames(plants1)] <- unlist(plants1)
}
# convert matrix to df 
degreedf <- as.data.frame(bigmat)
degreedf <- degreedf %>%
  rownames_to_column(var = "treatment") %>%
  inner_join(trtVersions, by = "treatment")

# find node specialisation for each plant/poll in each treatment 

nodemat <- matrix(NA, nrow = length(plist), ncol = length(allsp), dimnames = list(names(plist), allsp))
for (i in names(plist)) {
  NSval <- nodespec(plist[[i]], inf.replace = NA)
  plants <- NSval[[1]]
  polls <- NSval[[2]]
  NSnames <- names(c(plants,polls))
  nodemat[i,NSnames] <- c(plants,polls)
}

# convert matrix to df 
nodedf <- as.data.frame(nodemat)
nodedf <- nodedf %>%
  rownames_to_column(var = "treatment")%>%
  inner_join(trtVersions, by = "treatment")

# find specialization for each plant/poll in each treatment

dmat <- matrix(NA, nrow = length(plist), ncol = length(allsp), dimnames = list(names(plist), allsp))
for (i in names(plist)) {
  d <- specieslevel(plist[[i]], level = "both", index = "d")
  polls1 <- d$`higher level`
  plants1 <- d$`lower level`
  dmat[i,rownames(polls1)] <- unlist(polls1)
  dmat[i,rownames(plants1)] <- unlist(plants1)
}

# convert matrix to df 
ddf <- as.data.frame(dmat)
ddf <- ddf %>%
  rownames_to_column(var = "treatment")%>%
  inner_join(trtVersions, by = "treatment")

# make dfs long 
degreedf_long <- degreedf %>% 
  pivot_longer(cols = -c(treatment, genSpec),
               names_to = "species", values_to = "degree")

ddf_long <- ddf %>% 
  pivot_longer(cols = -c(treatment, genSpec),
               names_to = "species", values_to = "specialization")

nodedf_long <- nodedf %>% 
  pivot_longer(cols = -c(treatment, genSpec),
               names_to = "species", values_to = "ns")


# join species level df to poll and seeds df 
speciesDF <- pollsSeedsdf %>%
  rename(species = "Genus") %>%
  inner_join(degreedf_long, by = c("treatment","species","genSpec"), relationship = "many-to-many") %>%
  inner_join(nodedf_long, by = c("treatment","species","genSpec"), relationship = "many-to-many") %>%
  inner_join(ddf_long, by = c("treatment","species","genSpec"), relationship = "many-to-many")

species_long <- speciesDF %>%
  pivot_longer(cols = -c(genSpec, BP, treatment, specialization, ratio_seedsPerPlant, degree, ns), values_to = "spec") %>%
  select(-name) %>%
  select(genSpec, BP, treatment, spec, degree, specialization, ns, ratio_seedsPerPlant)
```

visualize species level characteristics: DEGREE 

```{r}

speciesDF %>%
    pivot_longer(cols = c(specialization, ns, degree, ratio_seedsPerPlant),
               names_to = "variable",
               values_to = "value") %>%
  
  ggplot(aes(x = genSpec, y = value, fill = variable)) +
  geom_col(position = "dodge") +
  theme(legend.position = "none") +
  scale_fill_paletteer_d("nationalparkcolors::ArcticGates") +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  labs(x = "Treatment", y = "Value", fill = "Variable")

# plot specalization for plants 
ddf_long %>% 
  filter(species %in% allplants)
ggplot(ddf_long, aes(x = specialization, fill = genSpec)) +
  #geom_histogram(alpha = 0.0, position = "identity", bins = 10) +
  geom_density(linewidth = 0.2, alpha = 0.5)

# plot degree for pollinators 
ddf_long %>%
  filter(species %in% allpolls)
ggplot(ddf_long, aes(x = specialization, fill = genSpec)) +
  #geom_histogram(alpha = 0.0, position = "identity", bins = 10) +
  geom_density(linewidth = 0.2, alpha = 0.5)

ggplot(species_long) +
  #geom_histogram(alpha = 0.0, position = "identity", bins = 10) +
  geom_point(aes(x = ns, y = ratio_seedsPerPlant, color = genSpec))
  #facet_wrap(~genSpec)

```

visualize species level characteristics: SPECIALIZATION 

```{r}
# plot specalization for plants 
ddf_long %>% 
  filter(species %in% allplants)
ggplot(ddf_long, aes(x = specialization, fill = genSpec)) +
  #geom_histogram(alpha = 0.0, position = "identity", bins = 10) +
  geom_density(linewidth = 0.2, alpha = 0.5)

# plot degree for pollinators 
ddf_long %>%
  filter(species %in% allpolls)
ggplot(ddf_long, aes(x = specialization, fill = genSpec)) +
  #geom_histogram(alpha = 0.0, position = "identity", bins = 10) +
  geom_density(linewidth = 0.2, alpha = 0.5)


```

Join network level to species level


```{r}
allCHAR <- speciesDF %>%
  rename(seedOutput = "ratio_seedsPerPlant") %>%
  inner_join(WIDEfocalSeeds, by = c("treatment", "seedOutput", "sp", "BP", "genSpec"), relationship = "many-to-many") %>%
  allCHAR <- allCHAR

allCHAR$genSpec <- gsub("genOnly", "Generalists", allCHAR$genSpec)
allCHAR$genSpec <- gsub("specOnly", "Specialists", allCHAR$genSpec)
allCHAR$genSpec <- gsub("genSpec1", "Mix1", allCHAR$genSpec)
allCHAR$genSpec <- gsub("genSpec3", "Mix2", allCHAR$genSpec)
allCHAR$genSpec <- gsub("genSpec4", "Mix3", allCHAR$genSpec)
allCHAR$Overlap <- allCHAR$AVoverlap
allCHAR$SeedOutput <- allCHAR$seedOutput

write.csv(allCHAR, file = "all_levels_characteristics.csv", col.names = FALSE)
write.csv(WIDEfocalSeeds1, file = "Wide_focals.csv", col.names = FALSE)




```
