---
title: "Visualisations"
output: html_document
date: "2026-03-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(paletteer)
library(tidyr)
library(dplyr)
library(bipartite)
library(ggplot2)
library(ggeffects)
library(ggrepel)
library(tidyverse)
library(vegan)
library(ggridges)
library(fmsb)
```


```{r pressure, echo=FALSE}
# Overlap against seed ratios for all treatments and species 
WIDEfocalSeeds1<- read.csv("Wide_focals.csv")
allCHAR<- read.csv("all_levels_characteristics.csv")

lm1 = lm(WIDEfocalSeeds$seedOutput~WIDEfocalSeeds$AVoverlap)
ggplot(WIDEfocalSeeds1, aes(x = AVoverlap, y = SeedOutput, color = genSpec, shape = sp)) +
  geom_point(size = 5, alpha = 0.9) +
  scale_shape_manual(values = c(15, 16, 17, 18, 19)) +
  scale_colour_paletteer_d("nationalparkcolors::ArcticGates") +
  #geom_abline(intercept = coef(lm1)[1], slope = coef(lm1)[2], color = "red") +
  #geom_text(aes(x = 0.75, y = 1.5, label = "p = 0.568"),color = "red", vjust = -1) +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  labs(x="Overlap", y = "Seed Output", color = "Treatment", shape = "Flower Species")
  #facet_wrap(~sp)


# plot visits against richness 
lm2 <- lm(WIDEfocalSeeds$richness~WIDEfocalSeeds$total_visits)
ggplot(WIDEfocalSeeds1, aes(x = total_visits, y = richness, color = genSpec)) +
  geom_point(size = 5, alpha = 0.8) +
  scale_shape_manual(values = c(15, 16, 17, 18, 19)) +
   scale_colour_paletteer_d("nationalparkcolors::ArcticGates") +
  geom_abline(intercept = coef(lm2)[1], slope = coef(lm2)[2], color = "red") +
   geom_text(aes(x = 75, y = 21, label = "p < 0.05"), 
            color = "red", vjust = -1) +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  labs(x="Visits", y = "Richness", color = "Treatment")

degreedf_long %>%
  filter(species %in% allpolls) %>%
ggplot(aes(x = degree, y = genSpec, group = genSpec)) + 
  geom_density_ridges(aes(fill = genSpec)) +
  scale_fill_paletteer_d("nationalparkcolors::ArcticGates") +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  labs(x = "Pollinator Degree", y = "Treatment", fill = "Treamtment")

ggplot(WIDEfocalSeeds1, aes(x = AVoverlap, y = genSpec, group = genSpec)) + 
  geom_density_ridges(aes(fill = genSpec)) +
  scale_fill_paletteer_d("nationalparkcolors::ArcticGates") +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  labs(x = "Overlap", y = "Treatment", fill = "Treamtment")

lm3 <- lm(species_long$ratio_seedsPerPlant~species_long$specialization)
ggplot(species_long) +
  geom_point(aes(x = specialization, y = ratio_seedsPerPlant, color = genSpec))+
  scale_color_paletteer_d("nationalparkcolors::ArcticGates") +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  geom_abline(intercept = coef(lm3)[1], slope = coef(lm3)[2], color = "red") +
  geom_text(aes(x = 0.75, y = 2, label = "p = 0.2077"), 
            color = "red", vjust = -1) +
  labs(x = "Species Specialization", y = "Seed Output", color = "Treamtment")

lm13 <- lm(WIDEfocalSeeds$seedOutput~WIDEfocalSeeds$H2)
ggplot(WIDEfocalSeeds1) +
  geom_point(aes(x = H2, y = SeedOutput, color = genSpec))+
  scale_color_paletteer_d("nationalparkcolors::ArcticGates") +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  geom_abline(intercept = coef(lm13)[1], slope = coef(lm13)[2], color = "red") +
  geom_text(aes(x = 0.6, y = 2, label = "p-vlaue = 0.2425"), 
            color = "red", vjust = -1) +
  labs(x = "Network Specialization", y = "Seed Output", color = "Treamtment")

lm8 <- lm(WIDEfocalSeedsPCA$seedOutput~WIDEfocalSeedsPCA$PC1)
ggplot(WIDEfocalSeedsPCA) +
  geom_point(aes(x = PC1, y = seedOutput, color = genSpec, shape = sp)) +
  scale_color_paletteer_d("nationalparkcolors::ArcticGates") +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  geom_abline(intercept = coef(lm8)[1], slope = coef(lm8)[2], color = "red") +
  geom_text(aes(x = -1.3, y = 2.7, label = "p = 0.4416"), 
            color = "red", vjust = -1) +
  labs(x = "PC1", y = "Seed Output", color = "Treatment", shape = "Flower Species")


ggplot(WIDEfocalSeedsPCA) +
  geom_point(aes(x = AVoverlap, y = PC2, color = genSpec))

lm0 <- lm(WIDEfocalSeeds$richness~WIDEfocalSeeds$AVoverlap)
lm11<- lm(WIDEfocalSeeds$total_visits~WIDEfocalSeeds$AVoverlap)

ggplot(WIDEfocalSeeds1, aes(x = AVoverlap, y = richness, color = genSpec)) +
  geom_point(size = 3, alpha = 0.9) +
  scale_colour_paletteer_d("nationalparkcolors::ArcticGates") +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  #geom_abline(intercept = coef(lm0)[1], slope = coef(lm0)[2], color = "red") +
  #geom_text(aes(x = 0.75, y = 12, label = "p = 0.6365"), color = "red", vjust = -1) +
  labs(x = "Overlap", y = "Pollinator Richness", color = "Treatment")

ggplot(WIDEfocalSeeds1, aes(x = AVoverlap, y = total_visits, color = genSpec)) +
  geom_point(size = 3, alpha = 0.9) +
  scale_colour_paletteer_d("nationalparkcolors::ArcticGates") +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  #geom_abline(intercept = coef(lm11)[1], slope = coef(lm11)[2], color = "red") +
  #geom_text(aes(x = 0.75, y = 29, label = "p = 0.2029"), color = "red", vjust = -1) +
  labs(x = "Overlap", y = "Pollinator Visitation", color = "Treatment")

# plot overlap for treatments
ggplot(WIDEfocalSeeds1, aes(x = genSpec, y = AVoverlap, fill = genSpec)) +
  geom_boxplot() +
  scale_fill_paletteer_d("nationalparkcolors::ArcticGates") +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  stat_summary(fun = mean, geom = "text", aes(label = round(..y.., 2)), vjust = -0.5) +
  labs(x="Treatment", y = "Overlap", fill = "Treatment") 


#plot seed ratios for treatments
ggplot(WIDEfocalSeeds1, aes(x = genSpec, y = SeedOutput, fill = genSpec)) +
  geom_boxplot() +
  scale_fill_paletteer_d("nationalparkcolors::ArcticGates") +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  stat_summary(fun = mean, geom = "text", aes(label = round(..y.., 2)), vjust = 1) +
  labs(x="Treatment", y = "Seed Output", fill = "Treatment")

WIDEfocalSeeds1 %>%
  group_by(genSpec) %>%
  summarise(meanfc = mean(seedOutput, na.rm = TRUE)) %>% 
ggplot(aes(y = meanfc, x = genSpec, fill = genSpec)) +
  geom_col() +
  scale_fill_paletteer_d("nationalparkcolors::ArcticGates") +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  labs(x="Treatment", y = "Seed Output", fill = "Flower Species")

ggplot(WIDEfocalSeeds1, aes(x = genSpec, y = richness, fill = genSpec)) +
  geom_boxplot() +
  scale_fill_paletteer_d("nationalparkcolors::ArcticGates") +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  stat_summary(fun = mean, geom = "text", aes(label = round(..y.., 2)), vjust = -.3) +
  labs(x="Treatment", y = "Pollinator Richness", fill = "Treatment") 

ggplot(WIDEfocalSeeds1, aes(x = genSpec, y = total_visits, fill = genSpec)) +
  geom_boxplot() +
  scale_fill_paletteer_d("nationalparkcolors::ArcticGates") +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  stat_summary(fun = mean, geom = "text", aes(label = round(..y.., 2)), vjust = 0.8) +
  labs(x="Treatment", y = "Pollinator Visitation", fill = "Treatment") 

#Total seed out put for all treatments 
ggplot(WIDEfocalSeeds1, aes(x = factor(genSpec, levels = c("Generalists", "Mix1", "Specialists", "Mix2", "Mix3")), y= seedOutput, fill = sp)) +
  geom_col(position = "stack") +
  coord_flip() +
  scale_fill_manual(values = c("#8B0069", "#A95F12", "#A38600", "#7BBB58")) +
  theme_bw(paper = "#f5f6f0") + 
    theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  labs(x = "Treatment", y = "Seed Output", fill = "Focal Species")

#nestedness and overlap for all treatments 
lm26 <- lm(WIDEfocalSeeds1$nestedness~WIDEfocalSeeds1$AVoverlap)
ggplot(WIDEfocalSeeds1, aes(x = AVoverlap, y = nestedness, color = genSpec)) +
  geom_point(size = 3, alpha = 0.9) +
  scale_colour_paletteer_d("nationalparkcolors::ArcticGates") +
  theme_bw(paper = "#f5f6f0") + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  geom_abline(intercept = coef(lm26)[1], slope = coef(lm26)[2], color = "red") +
  geom_text(aes(x = 0.75, y = 20, label = "p < 0.05"), color = "red", vjust = -1) +
  labs(x = "Overlap", y = "Nestedness", color = "Treatment")


```

SPEC only vs GEN only 

```{r}
genspecdf <- WIDEfocalSeeds1 %>%
  filter(genSpec == "Generalists" | genSpec == "Specialists")

lm25 <- lm(genspecdf$nestedness~genspecdf$AVoverlap)
ggplot(genspecdf, aes(x = AVoverlap, y = nestedness, color = genSpec)) +
  geom_point(size = 3, alpha = 0.9) +
  scale_colour_paletteer_d("nationalparkcolors::ArcticGates") +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  geom_abline(intercept = coef(lm25)[1], slope = coef(lm25)[2], color = "red") +
  geom_text(aes(x = 0.75, y = 20, label = "p < 0.05"), color = "red", vjust = -1) +
  labs(x = "Overlap", y = "Nestedness", color = "Treatment")

LongFOCAL <- WIDEfocalSeeds1 %>%
  pivot_longer(cols = c(Overlap, SeedOutput, richness, total_visits, H2, nestedness),
               names_to = "variable",
               values_to = "value")
LongFOCAL %>%
 filter(variable == "richness" | variable == "nestedness" | variable == "total_visits") %>%
ggplot(aes(x = genSpec, y = value, fill = genSpec))+
  geom_col(position = "dodge") +
  scale_fill_paletteer_d("nationalparkcolors::ArcticGates") +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  labs(x = "", y = "Value", fill = "Treatment") +
  facet_wrap(~variable) +
  theme(strip.background = element_blank(), axis.text.x = element_blank())

LongFOCAL %>%
 filter(variable == "nestedness" | variable == "SeedOutput") %>%
ggplot(aes(x = genSpec, y = value, fill = genSpec))+
  geom_col(position = "dodge") +
  scale_fill_paletteer_d("nationalparkcolors::ArcticGates") +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  labs(x = "", y = "Value", fill = "Treatment") +
  theme(strip.background = element_blank(), axis.text.x = element_blank())

ggplot(LongFOCAL, aes(x = AVoverlap, y = log(value), fill = variable, color = variable)) +
  geom_smooth(aes(group = variable))

totalmean <- mean(WIDEfocalSeeds1$seedOutput, na.rm = TRUE)
 geom_hline(aes(yintercept = totalmean))


    

  

```
pie charts all communities 

```{r}
#Make pollinator Pie chart 
pollCount <- pollinators %>%
  count(Genus, name = "n_occurrences")

vals <- pollCount$n_occurrences
labs <- pollCount$Genus

# hide labels for slices < 2% of the pie
pct <- vals / sum(vals)
labs[pct < 0.02] <- ""

pie(vals, radius = 1, labels = labs, col = cols, border = "white", main = "Genera of pollinator visitors to all communities", cex = 0.5)

# make plant pie chart 
seedCount <- pollinators %>%
  ungroup() %>%
  count(sp, name = "n")

vals <- seedCount$n
labs <- seedCount$sp

# hide labels for slices < 2% of the pie
pct <- vals / sum(vals)
labs[pct < 0.02] <- ""

pie(vals, radius = 1, labels = labs, col = cols, border = "white", main = "Species of plants visited by pollinators", cex = 0.5) +
   theme_bw(paper = "#f5f6f0") + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) 

# sum all seeds by sp
spseedsSUM <- bigseeds %>%
  group_by(sp) %>%
  filter(sp != "PC") %>%
  summarise(total = sum(total.seeds))

spseedsSUM$sp <- gsub("CA", "Clarkia amoena", spseedsSUM$sp)
spseedsSUM$sp <- gsub("CP", "Clarkia purpurea", spseedsSUM$sp)
spseedsSUM$sp <- gsub("ME", "Madia elegans", spseedsSUM$sp)
spseedsSUM$sp <- gsub("MG", "Microsteris gracilis", spseedsSUM$sp)


ggplot(spseedsSUM, aes(x = sp, y = total, fill = sp)) +
  geom_col(position = "dodge") +
  scale_fill_manual(values = c("#8B0069", "#A95F12", "#A38600", "#7BBB58")) +
  theme_bw() + 
  theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  labs(x = "Species", y = "Total number of seeds", fill = "Species")

bigseeds %>%
  group_by(sp) %>%
  tally()


ggplot(WIDEfocalSeeds1, aes(x = sp, y = seedOutput, color = genSpec)) +
 stat_summary(fun = mean, geom = "point", size = 2) 

meanssp <- WIDEfocalSeeds1 %>%
  group_by(sp) %>%
  summarise(meanseeds = mean(seedOutput, na.rm = TRUE))

ggplot(WIDEfocalSeeds1, aes(x = sp, y = seedOutput, color = genSpec)) +
  stat_summary(fun = mean, geom = "point", size = 5) +
  scale_color_paletteer_d("nationalparkcolors::ArcticGates") +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  geom_point(data = meanssp, aes(x = sp, y = meanseeds), color = "black") +
  geom_hline(slope = 0, yintercept = 1, linewidth = 1, color = "black", linetype = "dotted") +
  geom_text(aes(x = 4, y = 1, label = "positive pollinator impact"), color = "black", vjust = -1, cex = 3) +
 # facet_wrap(~sp, scales = "free") +
    #theme(strip.background = element_blank(), axis.text.x = element_blank(), vjust = -3) +
  labs(x = "Focal Species", y = "Seed Output", color = "Treatment")
  
```

